name: Build, lint, test, and upload to PyPI

on:
  push:
    branches:
      - main

jobs:
  build-3-10:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools wheel twine autopep8
      - name: Lint with autopep8
        run: |
          python3 -m autopep8 -rd base/ operators/
      - name: Build package
        run: |
          python3 setup.py sdist

  build-3-9:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools wheel twine autopep8
      - name: Lint with autopep8
        run: |
          python3 -m autopep8 -rd base/ operators/
      - name: Build package
        run: |
          python3 setup.py sdist

  build-3-8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools wheel twine autopep8
      - name: Lint with autopep8
        run: |
          python3 -m autopep8 -rd base/ operators/
      - name: Build package
        run: |
          python3 setup.py sdist

  build-3-7:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools wheel twine autopep8
      - name: Lint with autopep8
        run: |
          python3 -m autopep8 -rd base/ operators/
      - name: Build package
        run: |
          python3 setup.py sdist

  build-3-6:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools wheel twine autopep8
      - name: Lint with autopep8
        run: |
          python3 -m autopep8 -rd base/ operators/
      - name: Build package
        run: |
          python3 setup.py sdist

  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.filter.outputs.modules }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          modules:
            - 'base/**'
            - 'operators/**'

  deploy:
    needs:
      - build-3-10
      - build-3-9
      - build-3-8
      - build-3-7
      - build-3-6
    if: needs.paths-filter.outputs.output1 == 'true'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools wheel twine autopep8
      - name: Build package
        run: |
          python3 setup.py sdist
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
